In [4]:
import torch
from torch.utils.data import Dataset , DataLoader


from sklearn.datasets import make_classification

In [8]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

X = torch.tensor(X , dtype = torch.float32)
y = torch.tensor(y , dtype = torch.long)

In [18]:
class CustomDataset(Dataset):
    
    def __init__(self , features , labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self , index):
        return self.features[index] , self.labels[index]


In [19]:
dataset = CustomDataset(X , y)

In [20]:
print(len(dataset))

10


In [21]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [32]:
data_loader = DataLoader(dataset , batch_size = 2 , shuffle = True)

for X_train_batch , y_train_batch in data_loader:
    print(X_train_batch , '\n' , y_train_batch , "\n\n")

tensor([[ 1.0683, -0.9701],
        [-0.9382, -0.5430]]) 
 tensor([1, 1]) 


tensor([[-2.8954,  1.9769],
        [ 1.8997,  0.8344]]) 
 tensor([0, 1]) 


tensor([[-0.7206, -0.9606],
        [-0.5872, -1.9717]]) 
 tensor([0, 0]) 


tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]]) 
 tensor([0, 1]) 


tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]]) 
 tensor([0, 1]) 


